- name: Cinder installation
  apt:
    name:
      - cinder-api
      - cinder-backup
    state: present
    update_cache: yes

- name: Cinder configuration
  copy:
    dest: /etc/cinder/cinder.conf
    content: |
      [DEFAULT]
      auth_strategy = keystone
      [keystone_authtoken]
      www_authenticate_uri = http://controller:5000
      auth_url = http://controller:5000
      memcached_servers = controller:11211
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      project_name = service
      username = Cinder
      password = 123456789

- name: Starting Cinder
  service:
     name: cinder-backup
     state: restarted
     enabled: yes
